# Generated by Django 5.1.5 on 2025-02-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidyapath_project', '0002_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='rollNo',
        ),
        migrations.AddField(
            model_name='registration',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
