# Generated by Django 5.1.5 on 2025-02-28 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidyapath_project', '0003_remove_registration_rollno_registration_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('logo_url', models.CharField(max_length=500)),
                ('details_url', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PlacedStudent',
            fields=[
                ('student_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=255)),
                ('placement_year', models.IntegerField()),
                ('salary_lpa', models.FloatField()),
                ('photo_url', models.CharField(default='static/media/achivers/Designer(1).png', max_length=500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vidyapath_project.company')),
            ],
        ),
    ]
