# Generated by Django 5.1.7 on 2025-03-28 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidyapath_project', '0005_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placedstudent',
            name='photo_url',
        ),
    ]
