# Generated by Django 5.1.7 on 2025-03-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidyapath_project', '0006_remove_placedstudent_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedstudent',
            name='photo',
            field=models.ImageField(blank=True, default='achievers/Designer_1.png', null=True, upload_to='achievers/'),
        ),
    ]
