# Generated by Django 5.1.5 on 2025-04-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidyapath_project', '0007_placedstudent_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
