# Generated by Django 5.1.5 on 2025-04-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidyapath_project', '0008_registration_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
