# Generated by Django 5.1.7 on 2025-04-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidyapath_project', '0009_alter_registration_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedstudent',
            name='branch',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
